# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://localhost:7029

###

GET https://localhost:7029/Home/Login

###
GET https://localhost:7029/Home/Privacy

###

Post https://localhost:7029/register
Content-Type: application/json

{
  "email": "string@gmail.com",
  "password": "string-0Z"
}

###

DELETE https://localhost:7099/todos/1
